name: Tests
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  macOS:
    name: "macOS 15"
    runs-on: macos-15
    steps:
      - run: | 
         brew install podman
         podman machine init
         podman machine start
         podman run hello-world
        
